### ISSUE TITLE
Lot of errors showing up in atom

### ISSUE THREAD

**Issue by Roviluca** [AtomLinter/linter-foodcritic#17]
Since some day, after an update in linter-foodcritic and linter (as far as i remember), lot of error boxes started to show up in atom.

> Error: Line number (219) greater than maximum line (49)
> Error: Line number (219) greater than maximum line (49)
>     at Object.rangeFromLineNumber (C:\Users\username.atom\packages\linter-foodcritic\node_modules\atom-linter\lib\helpers.js:153:11)
>     at file:///C:/Users/username/.atom/packages/linter-foodcritic/lib/main.coffee:54:30
>     at process._tickCallback (node.js:368:9)

and another one:

> Error: Line number (255) greater than maximum line (49)
> Error: Line number (255) greater than maximum line (49)
>     at Object.rangeFromLineNumber (C:\Users\username.atom\packages\linter-foodcritic\node_modules\atom-linter\lib\helpers.js:153:11)
>     at file:///C:/Users/username
> /.atom/packages/linter-foodcritic/lib/main.coffee:54:30
>     at process._tickCallback (node.js:368:9)

and here the screenshot:
![untitled](https://cloud.githubusercontent.com/assets/7407203/11778115/b542def2-a252-11e5-930c-d4a01c30d627.png)

**Comment by ndobson** [comment]
Yeah I've notice that, I believe linter-foodcritic is trying to markup all files with each finding instead of only marking up the file with the finding.

I'm working on a fix.

**Comment by Roviluca** [comment]
ok, thank you.
And, by the way, thank you very much for this plugin.

**Comment by ndobson** [comment]
@Roviluca try release 0.5.1, should be fixed.

**Comment by vegardx** [comment]
I'm still seeing this, tried both 0.5.1 and 0.5.2 using the latest version of linter and language-chef.

**Comment by Arcanemagus** [comment]
@vegardx Do you have an example file/project to run this on? This should have been fixed in v0.5.1.

**Comment by vegardx** [comment]
This recipe triggers the error for me. The "Line number" can change to anywhere around the total amount of lines.

https://gist.github.com/vegardx/cc93d664ae5227190fa3

**Comment by miguelaferreira** [comment]
I'm seeing the same issue as @vegardx 

linter, linter-foodcritic and language-chef all installed today at latest release versions.

**Comment by mrx88** [comment]
I have similar issue:

Error: Line number (43) greater than maximum line (22)
Error: Line number (43) greater than maximum line (22)
    at Object.rangeFromLineNumber (/home/username/.atom/packages/linter-foodcritic/node_modules/atom-linter/lib/index.js:179:11)
    at /home/username/.atom/packages/linter-foodcritic/lib/main.coffee:54:30
    at process._tickCallback (node.js:368:9)

 Installed versions:
linter-foodcritic 0.5.2
linter 1.11.3
language-chef 0.8.0
foodcritic 6.0.0 (installed using ChefDK)

I'm using linux (Debian Wheezy).
Any ideas?
